baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'hugo-theme-relearn'
menuPre = "<i class='fab fa-github'>github</i> "

[params]
themeVariant = [
  	{ identifier = "neon"           },
	{ identifier = "green"          },
	{ identifier = "relearn-auto",  name = "Relearn Light/Dark", auto = [] },
	{ identifier = "relearn-light"  },
	{ identifier = "relearn-dark"   },
	{ identifier = "relearn-bright" },
	{ identifier = "zen-auto",      name = "Zen Light/Dark", auto = [ "zen-light", "zen-dark" ] },
	{ identifier = "zen-light"      },
	{ identifier = "zen-dark"       },
	{ identifier = "learn"          },
	{ identifier = "blue"           },
	{ identifier = "red"            }
]